project_id = "bwmkqcbfkuqmzhvqrxzo"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true

[db]
port = 54323

[storage]
enabled = true
port = 54324
image_transformation = { enabled = true }

[edge_runtime]
enabled = true
port = 54325

[analytics]
enabled = false

[functions.ai-chat]
verify_jwt = true

[functions.ai-realtime]
verify_jwt = true

[functions.cscs-card-analyzer]
verify_jwt = true