// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwmkqcbfkuqmzhvqrxzo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3bWtxY2Jma3VxbXpodnFyeHpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDMyOTgsImV4cCI6MjA2NDY3OTI5OH0.vv6ko6oTOpVM2Fv6x_BVv3VRCoZ5AWzCwoVb3Rnnfo4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});